import telegram
from telegram.ext.dispatcher import run_async
from telegram.utils.request import Request
from telegram.ext import Updater, Dispatcher
import datetime
import toml
import time
from random import choice


config = toml.load('config.toml')
bot = telegram.Bot(config.get('token'), request=Request(con_pool_size=70, connect_timeout=120))
image_urls = [
    'https://i.imgur.com/72oDVSW.jpg',
    'https://i.imgur.com/4xBs4JD.png',
    'https://i.imgur.com/L3KOxC1.png',
    'https://i.imgur.com/KLwpdtl.png',
    'https://i.imgur.com/PLo4flf.png',
    'https://i.imgur.com/PhZXXzz.png',
    'https://i.imgur.com/0Vxl9PQ.png',
    'https://i.imgur.com/9B0uvwH.png',
    'https://i.imgur.com/6QkPpAk.png',
    'https://i.imgur.com/DInU3zd.png',
    'https://i.imgur.com/INiIOi5.png',
    'https://i.imgur.com/ba2EIVv.png',
    'https://i.imgur.com/FmvBDab.png',
    'https://i.imgur.com/MrgVFVf.png',
    'https://i.imgur.com/AtcqOJs.png',
    'https://i.imgur.com/Nu0MwGw.png',
    'https://i.imgur.com/EMXYxqO.jpg',
    'https://i.imgur.com/Y0Dd8qg.png',
    'https://i.imgur.com/xjA2KRU.png',
    'https://i.imgur.com/ecRk8Ro.png',
    'https://i.imgur.com/7MazOMl.png',
    'https://i.imgur.com/rocfpta.png',
    'https://i.imgur.com/ELgNNZc.png',
    'https://i.imgur.com/MyXKXyd.png',
    'https://i.imgur.com/v1ciCWX.png',
    'https://i.imgur.com/ISba2sf.png',
    'https://i.imgur.com/cUEJDkC.png',
    'https://i.imgur.com/7wM4KBk.png',
    'https://i.imgur.com/P7AmXnZ.png',
    'https://i.imgur.com/ykYjAWX.png',
    'https://i.imgur.com/zBR3aBy.png',
    'https://i.imgur.com/W105rQZ.png',
    'https://i.imgur.com/iX3cCN3.png',
    'https://i.imgur.com/ZIOQNv3.png',
    'https://i.imgur.com/htDccY6.png',
    'https://i.imgur.com/lgxQ2m0.png',
    'https://i.imgur.com/MMlCoQi.png',
    'https://i.imgur.com/RvTm4Eb.png',
    'https://i.imgur.com/gTRsgmx.png',
    'https://i.imgur.com/EhuyWfg.png',
    'https://i.imgur.com/c2YHKNc.png',
    'https://i.imgur.com/I0Bho7G.png',
    'https://i.imgur.com/JbtpcpL.png',
    'https://i.imgur.com/hEZNiMR.png',
    'https://i.imgur.com/ab82HGk.png',
    'https://i.imgur.com/sHa7Uqc.png',
    'https://i.imgur.com/JNuek2Z.png',
    'https://i.imgur.com/8mtRNmB.png',
    'https://i.imgur.com/qt7nepa.png',
    'https://i.imgur.com/SXmjNZ2.png',
    'https://i.imgur.com/FpZkHa7.png',
    'https://i.imgur.com/g180zzQ.png',
    'https://i.imgur.com/Uzp2z2R.png',
    'https://i.imgur.com/eJCIMWZ.png',
    'https://i.imgur.com/HVXKoAA.png',
    'https://i.imgur.com/N4tGqkd.png',
    'https://i.imgur.com/iaXZwNj.png',
    'https://i.imgur.com/G5Wl5O4.png',
    'https://i.imgur.com/Y1hD22P.png',
    'https://i.imgur.com/ihPhln6.png',
    'https://i.imgur.com/OO7ozdf.png',
    'https://i.imgur.com/EaXIPBI.png',
    'https://i.imgur.com/lDCIRVk.png',
    'https://i.imgur.com/TJeaT85.png',
    'https://i.imgur.com/AiFTkaT.png',
    'https://i.imgur.com/SibXa3w.png',
    'https://i.imgur.com/y4sPYf5.png',
    'https://i.imgur.com/4olXVfp.png',
    'https://i.imgur.com/bH41ymQ.png',
    'https://i.imgur.com/rwsN6gJ.png',
    'https://i.imgur.com/AOdYg03.png',
    'https://i.imgur.com/KJKo1V5.png',
    'https://i.imgur.com/kPVd5wO.png',
    'https://i.imgur.com/aJYqo4H.png',
    'https://i.imgur.com/glGkBhX.png',
    'https://i.imgur.com/7FRw15U.png',
    'https://i.imgur.com/ITHd0rG.png',
    'https://i.imgur.com/X7uAwvf.png',
    'https://i.imgur.com/JnEfuml.png',
    'https://i.imgur.com/GWLf8YI.png',
    'https://i.imgur.com/roH4Ssc.png',
    'https://i.imgur.com/5brwNhw.png',
    'https://i.imgur.com/B59AEKW.png',
    'https://i.imgur.com/pKu6Uhr.png',
    'https://i.imgur.com/kLzkivL.png',
    'https://i.imgur.com/8jaZMKr.png',
    'https://i.imgur.com/xeukhQP.png',
    'https://i.imgur.com/JgXxeyT.png',
    'https://i.imgur.com/FtEIzjC.png',
    'https://i.imgur.com/cPNaVwr.png',
    'https://i.imgur.com/qNakYvQ.png',
    'https://i.imgur.com/oW3nGWV.png',
    'https://i.imgur.com/uKE8sK0.png',
    'https://i.imgur.com/H3hSsia.png',
    'https://i.imgur.com/XdfH76j.png',
    'https://i.imgur.com/w5EbGFD.png',
    'https://i.imgur.com/46JNyBS.png',
    'https://i.imgur.com/KsD8Jtn.png',
    'https://i.imgur.com/XhOfHQr.png',
    'https://i.imgur.com/gPxo3mv.png',
    'https://i.imgur.com/pBFiE97.png',
    'https://i.imgur.com/N1VjtJx.png',
    'https://i.imgur.com/PGLJgVp.png',
    'https://i.imgur.com/iS8sdlS.png',
    'https://i.imgur.com/mId9y5I.png',
    'https://i.imgur.com/iGPH74x.png',
    'https://i.imgur.com/GRH5Wkp.png',
    'https://i.imgur.com/dJlLmrx.png',
    'https://i.imgur.com/N8jAV6K.png',
    'https://i.imgur.com/RTA1qQX.png',
    'https://i.imgur.com/rICVrOw.png',
    'https://i.imgur.com/QCmjIwJ.png',
    'https://i.imgur.com/bQ9N4DI.png',
    'https://i.imgur.com/rzp2oC2.png',
    'https://i.imgur.com/t0vkfQv.png',
    'https://i.imgur.com/Mb3pB9O.png',
    'https://i.imgur.com/ZmpZV4s.png',
    'https://i.imgur.com/4ViXjnP.jpg',
    'https://i.imgur.com/qDw4BxF.png',
    'https://i.imgur.com/wY0al0n.png',
    'https://i.imgur.com/M6gHlCT.png',
    'https://i.imgur.com/TLkmp5I.png',
    'https://i.imgur.com/RPjmS8P.png',
    'https://i.imgur.com/M3ssaG1.png',
    'https://i.imgur.com/1TDBrL9.png',
    'https://i.imgur.com/imCORhU.png',
    'https://i.imgur.com/YOVgx4V.png',
    'https://i.imgur.com/FA7oLF3.png',
    'https://i.imgur.com/uoyHTUw.png',
    'https://i.imgur.com/jrWc1oD.png',
    'https://i.imgur.com/RbucXBg.png',
    'https://i.imgur.com/OJuubO8.png',
    'https://i.imgur.com/mnBeFLY.png',
    'https://i.imgur.com/f0ydFgE.png',
    'https://i.imgur.com/KmoJIAY.png',
    'https://i.imgur.com/6ipdv0N.png',
    'https://i.imgur.com/YooIeoW.png',
    'https://i.imgur.com/uWgAkAJ.png',
    'https://i.imgur.com/QVb5hAM.png',
    'https://i.imgur.com/X9LlTZF.png',
    'https://i.imgur.com/guXccfK.png',
    'https://i.imgur.com/60iNAos.png',
    'https://i.imgur.com/Ft9fAbL.png',
    'https://i.imgur.com/2xrxLM5.png',
    'https://i.imgur.com/TuJhMek.png',
    'https://i.imgur.com/mi7DF86.png',
    'https://i.imgur.com/mhDGUla.png',
    'https://i.imgur.com/mWCkvlT.png',
    'https://i.imgur.com/mCP9ciC.png',
    'https://i.imgur.com/vlJuUTv.png',
    'https://i.imgur.com/Oowtfr6.png',
    'https://i.imgur.com/ujidQzZ.png',
    'https://i.imgur.com/K7cYYnv.png',
    'https://i.imgur.com/M2ud2Ke.png',
    'https://i.imgur.com/7IsKUdH.png',
    'https://i.imgur.com/CE4Whw2.png',
    'https://i.imgur.com/RS6ENZx.png',
    'https://i.imgur.com/LZXGoN6.png',
    'https://i.imgur.com/c2QmYtY.png',
    'https://i.imgur.com/FlpT4PV.png',
    'https://i.imgur.com/8JT9k45.png',
    'https://i.imgur.com/0PyJqaw.png',
    'https://i.imgur.com/fZb597j.png',
    'https://i.imgur.com/7fVypBQ.png',
    'https://i.imgur.com/G9sEreJ.png',
    'https://i.imgur.com/D5ILrX2.png',
    'https://i.imgur.com/bINKNJH.png',
    'https://i.imgur.com/sFqHdb1.png',
    'https://i.imgur.com/NjTYMf7.png',
    'https://i.imgur.com/GRATIE9.png',
    'https://i.imgur.com/xxU67B7.png',
    'https://i.imgur.com/euQuMKb.png',
    'https://i.imgur.com/dmoKXW6.png',
    'https://i.imgur.com/jmkFS0K.png',
    'https://i.imgur.com/B0Ryyt5.png',
    'https://i.imgur.com/NPlwPFq.png',
    'https://i.imgur.com/QirKzJY.png',
    'https://i.imgur.com/Ax8rxHd.png',
    'https://i.imgur.com/4THkR0k.png',
    'https://i.imgur.com/Jq2xxKR.png',
    'https://i.imgur.com/TEntLIk.png',
    'https://i.imgur.com/p27AVrT.png',
    'https://i.imgur.com/SNOHufp.png',
    'https://i.imgur.com/DLjNp9J.png',
    'https://i.imgur.com/kVqh8mY.png',
    'https://i.imgur.com/qHVh8LT.png',
    'https://i.imgur.com/DYf3cyy.png',
]


@run_async
def hourly():
    while True:
        while datetime.datetime.utcnow().minute == 0 and datetime.datetime.utcnow().second == 0:
            image_url = choice(image_urls)
            bot.send_photo(config.get('channel'), image_url)
            time.sleep(1)
        time.sleep(1)


def main():
    updater = Updater(bot=bot, workers=66, use_context=True)
    updater.start_polling()
    print(f'Signed in as {bot.name}')
    hourly()
    updater.idle()


if __name__ == '__main__':
    main()
